on:
  pull_request:
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'

name: Test 1

jobs:
  test1:
    name: Test 1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Echo
        run: |
          echo $GITHUB_REF_NAME
          echo $GITHUB_SHA
          echo $GITHUB_HEAD_REF
          CHANGED_JS_FILES=$(git diff --diff-filter=ACMRT --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | egrep ".jsx?$|.ts?$" | xargs)
          echo "CHANGED_JS_FILES=$(echo $CHANGED_JS_FILES)" >> $GITHUB_ENV
          echo $CHANGED_JS_FILES

      - name: Another Echo
        run: echo $CHANGED_JS_FILES
